name: soter_flutter_blue
description: A new Flutter project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0
  flutter_blue:
    git:
      url: https://github.com/egbred/flutter_blue.git
      ref: a73f4eba042e062027b5fb9681cc8b1ba336610f

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.soteranalytics.soter_flutter_blue
        pluginClass: SoterFlutterBluePlugin
      ios:
        pluginClass: SoterFlutterBluePlugin
      windows:
        pluginClass: SoterFlutterBluePlugin